name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions: write-all

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install --force

      - name: Build
        run: npm run build
        env:
          # Set the base path for GitHub Pages
          NEXT_PUBLIC_BASE_PATH: /web
          # Disable telemetry during the build
          NEXT_TELEMETRY_DISABLED: 1

      - name: Export
        run: npm run export

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch the action should deploy to.
          folder: out  # The folder the action should deploy.
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication.
